menu:
  Home: /
  Archives: /archives
  page:
    归档: archives
    关于我: about

excerpt_link: Continue →

mathjax: false
fancybox: true

social:
  weibo: true
  facebook: true
  github: true
  rss: true

weibo:
  userid: 2361837077

facebook:
  username: xiaolong.luo.77

github:
  username: smalldragonluo

addit:
  facebook: false
  twitter: false
  gplus: false
  pinit: false
  publid:

duoshuo: smalldragonluo



